name: Debug Build

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Show Node.js version
        run: node --version

      - name: Show npm version
        run: npm --version

      - name: Show package.json
        run: cat package.json

      - name: Install dependencies
        run: npm ci

      - name: Show installed packages
        run: npm list --depth=0

      - name: Try build with verbose output
        run: npm run build --verbose

      - name: Show dist directory
        run: |
          echo "Dist directory contents:"
          ls -la dist/ || echo "Dist directory does not exist"
